export class Routes {
  static readonly ONBOARDING: string = 'pages/OnboardingPage';
  static readonly FILE_BROWSER: string = 'pages/FileBrowserPage';
  static readonly ITEM_DETAILS: string = 'pages/ItemDetailsPage';
  static readonly SETTINGS: string = 'pages/SettingsPage';
  static readonly PRIVACY_POLICY: string = 'pages/PrivacyPolicyPage';
  static readonly PRIVACY_VIEWER: string = 'pages/PrivacyPolicyViewerPage';
}